server:
  port: ${PORT:9060}
spring:
  application:
    name: users.vehicle
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      base-path: /
    exposure:
      include: metrics,health
    metrics:
      enabled: true
    health:
      show-details: always
      main:
        allow-circular-references: true

feign:
  client:
    config:
      email-client:
        url: http://localhost:9090

generator-new-user:
  url: "v1/api/clientes/users/register"

should-search-by-name:
  url: "v1/api/clientes/users/search"

shold-update-user-and-car:
  url: "v1/api/clientes/users/altera-os-dados"

should-delete-a-user-and-vehicle-by-its-id:
  url: "v1/api/clientes/users/deletar/1"

shold-return-ok-user-login:
  url: "v1/api/clientes/users/login-user"

shold-return-car-data-by-your-license-plate:
  url: "v1/api/clientes/users/search/license-plate"

must-change-the-license-plate-of-a-vehicle-that-was-registered-wrong:
  url: "v1/api/clientes/users/alter/license-plate"

must-change-the-model-of-a-vehicle-that-was-registered-incorrectly:
  url: "v1/api/clientes/users/alter/vehicle-model"

token-experation: 600_00
token-password:  c5b9c3de-8930-43e5-b6ef-1dccfda1b8f0