server:
  port: ${PORT:9060}
spring:
  application:
    name: users.vehicle
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      base-path: /
    exposure:
      include: metrics,health
    metrics:
      enabled: true
    health:
      show-details: always
      main:
        allow-circular-references: true

feign:
  client:
    config:
      email-client:
        url: http://localhost:9090

token-experation: 600_00
token_password:  c5b9c3de-8930-43e5-b6ef-1dccfda1b8f0


